-- Tolfa Booking — local POC database
CREATE DATABASE IF NOT EXISTS tolfa_poc CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tolfa_poc;

CREATE TABLE IF NOT EXISTS hrbs_area (
  id        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  area_name VARCHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hrbs_slot (
  id        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  area_id   INT UNSIGNED NOT NULL,
  slot_name VARCHAR(32) NOT NULL,
  capacity  TINYINT UNSIGNED NOT NULL DEFAULT 4
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hrbs_member (
  id        INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  mid       INT UNSIGNED NOT NULL DEFAULT 0,
  username  VARCHAR(64) NOT NULL,
  family    VARCHAR(64) NOT NULL,
  email1    VARCHAR(128) NOT NULL,
  password  VARCHAR(64) NOT NULL DEFAULT '',
  privmask  TINYINT UNSIGNED NOT NULL DEFAULT 3
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hrbs_entry (
  id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slot_id      INT UNSIGNED NOT NULL,
  pid          INT UNSIGNED NOT NULL,
  family       VARCHAR(64) NOT NULL,
  initials     VARCHAR(8)  NOT NULL DEFAULT '',
  start_time   INT UNSIGNED NOT NULL DEFAULT 0,
  end_time     INT UNSIGNED NOT NULL DEFAULT 0,
  type         CHAR(1) NOT NULL DEFAULT 'M',
  adult        TINYINT UNSIGNED NOT NULL DEFAULT 1,
  child12      TINYINT UNSIGNED NOT NULL DEFAULT 0,
  child00      TINYINT UNSIGNED NOT NULL DEFAULT 0,
  amount_due   INT NOT NULL DEFAULT 0,
  amount_res   INT NOT NULL DEFAULT 0,
  comment      TEXT,
  spfymf       TINYINT UNSIGNED NOT NULL DEFAULT 0,
  billing_1    VARCHAR(128) DEFAULT NULL,
  billing_2    VARCHAR(128) DEFAULT NULL,
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hrbs_cost (
  id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  type         CHAR(1) NOT NULL,
  label        VARCHAR(64) NOT NULL,
  adult_low    INT NOT NULL DEFAULT 0,
  adult_high   INT NOT NULL DEFAULT 0,
  child_low    INT NOT NULL DEFAULT 0,
  child_high   INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hrbs_config (
  id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  cfg_key      VARCHAR(64) NOT NULL UNIQUE,
  cfg_value    VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
